project_id = "vezubuket"

[functions.telegram-notify]
verify_jwt = false

[functions.amocrm-create-lead]
verify_jwt = false

[functions.yandex-yml]
verify_jwt = false

[functions.import-image]
verify_jwt = false
