project_id = "ljkfuyxxxaqevsxeswrv"

[functions.telegram-notify]
verify_jwt = false

[functions.amocrm-create-lead]
verify_jwt = false

[functions.yandex-yml]
verify_jwt = false

[functions.sitemap]
verify_jwt = false
